name: Generate tag version
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: Test token access
        env:
         TOKEN: ${{ secrets.GH_PAT }}
        run: |
         curl -s -H "Authorization: token ${TOKEN}" https://api.github.com/user

      - name: Push new version tag to repository
        env:
         TOKEN: ${{ secrets.GH_PAT }}
        run: |
         git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
         git push origin main --follow-tags
